apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
# selector.matchLabels provided via Kustomize
  template:
    spec:
      containers:
        - name: api-gateway
          image: europeana/api-gateway
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: api-gateway-config

