apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          # required to use local image
          imagePullPolicy: Never